### ISSUE TITLE
manage composed tense

### ISSUE THREAD

**Issue by allan-simon** [allan-simon/verbiste-android#3]
some tense in french are made with an auxilliary verb which is not supported by the data from Verbiste.

**Comment by allan-simon** [comment]
currently we support  composed tense for indicative mode

**Comment by cireficc** [comment]
I'm not too familiar with the project, but it would seem that composed tenses are actually the easiest to conjugate (algorithmically). You just need *avoir* or *être* conjugated for the appropriate subject/mood - e.g., first person singular conditional - then just add the past participle of the main verb.

**Comment by allan-simon** [comment]
actually you need the extra medata to know if the verb is conjugated with avoir or être (sometimes it can be both) and in case of être, you need to modify the part particle accordingly ,  also if you have a compound verb (se laver) you need to modify it properly. Far from being difficult, but missing some metadata I guess

**Comment by cireficc** [comment]
@allan-simon Yep all the reflexive verbs take *être*, and only [17 'normal' verbs that conjugate with *être*](https://frenchcrazy.com/2012/06/dr-mrs-vandertramp.html) (all the rest are *avoir*). If the metadata doesn't exist for this in Verbiste XML, then it must be hardcoded in the desktop version, and thus should be in Android as well, right?

As for the verbs that can conjugate with both auxiliaries, it seems that it's only a [short list of 6 verbs](https://www.cliffsnotes.com/study-guides/french/french-i/french-i-the-passe-compose/special-verbs-that-use-etre-and-avoir), which can also be hard-coded. I don't like the idea of hard-coding, but given that there's very little diversity in the metadata here, and that it only applies to a very small minority of verbs, I think it's warranted.

Reflexive verbs can also be regex detected with `(s'|se\s)`.

**Comment by allan-simon** [comment]
I forgot to close this issue and forgot to say that I did actually use your list of 17 verbs :) 

https://github.com/allan-simon/verbiste-cordova now the project is living there (and I need to backport that part) thanks again for your help
