### ISSUE TITLE
new version of verbist for android

### ISSUE THREAD

**Issue by oupala** [allan-simon/verbiste-android#8]
When trying to install Verbist for an android 9 device, I get the following warning:

![photo5848030936728449624](https://user-images.githubusercontent.com/13458743/72761563-ad074480-3bdc-11ea-9b7e-a41ec7b75f7c.jpg)

Could it be possible to upgrade the F-Droid package or the Verbist repository so that the app can be used on recent android without warning?

**Comment by allan-simon** [comment]
hello, thanks for the issue, unfortunately it has been a long time since I developed this application, so I don't know what I need to upgrade, if you can find this information , I will make the according change :)

**Comment by allan-simon** [comment]
i've made a pull request also in f-droid repository https://gitlab.com/fdroid/fdroiddata/merge_requests/6246/diffs so that the problem can be solved

**Comment by oupala** [comment]
Thanks a lot for the time you passed in trying to fix this problem.

Thanks also to @forrestguice for working on this.

**Comment by allan-simon** [comment]
yes without @forrestguice  I would have not known where to start ^^'

**Comment by oupala** [comment]
Can you tell us what is the status of the update?

**Comment by allan-simon** [comment]
I just need to find the motivation 5 minutes to rebase my fork in-fdroid :/

**Comment by roshavagarga** [comment]
Any update on the search for motivation? This is the only conjugation app on F-Droid for French :)

**Comment by allan-simon** [comment]
haha yes unfortunately , my fork in gitlab has some conflict , and it would be quicker to recreate the fork in f-droid's gitlab for the build of my project, but I can't recreate a fork ....

**Comment by allan-simon** [comment]
any help on this would be greatly appreciated ^^

**Comment by roshavagarga** [comment]
Ping Licaon in the merge request :)

**Comment by roshavagarga** [comment]
In case you were wondering what the merge request is - it's [this one](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6246)

**Comment by oupala** [comment]
@allan-simon Did you get the help you needed?

**Comment by allan-simon** [comment]
not yet I haven't get time these last month to look more into it :(

**Comment by gargamel17** [comment]
Application ils now available on f-droid, thank you

**Comment by allan-simon** [comment]
did somebody do something on f-droid ?

**Comment by gargamel17** [comment]
Hello Allan-Simon, 
Three years later, we get the same issue 🥳
Do you think you will update your lively app to be compliant with current android version, or you definitely dropped the maintenance ?
As previously said your app is unique.
Thanks

**Comment by allan-simon** [comment]
I'm still an active developer in general, so I will happily review patch but I don't think I will myself take the time to find how to patch it 
If I was to take back again the development of such an app, I would certainly start from scratch and see to package it as an offline embedded webpage.

1. it's very easy to manipulate even very large xml data file (and here the source data files are xml) with javascript, which would remove the need for a pre-compilation steps
2. it's much easier (at least for me) to style the pages (the screenshot for this app are very clear it about it :P )
3. easier to have a development environment installed

**Comment by allan-simon** [comment]
I may try to redo the app this weekend as a cordova app (I'm much much more familiar with react native/expo these days but I think f-droid does not like them ^^)

**Comment by allan-simon** [comment]
spoiler alert 

![image](https://github.com/allan-simon/verbiste-android/assets/213167/b2cc4fe4-f727-4935-9792-2dc68b36257c)

**Comment by allan-simon** [comment]
it's happening here https://github.com/allan-simon/verbiste-cordova :)

**Comment by allan-simon** [comment]
I've published an apk and i think i got all the features back , I'm cloing these issues and archiving this project :)

**Comment by gargamel17** [comment]
Thank you very much Allan 👍
